DEBUG 2019-04-21 03:39:31,337: 	 Executing command: 'getlog'
DEBUG 2019-04-21 03:39:31,337: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
ERROR 2019-04-21 03:39:31,338: 	 Error: crab_Run2018A/crab_Bparking_Run2018Als is not a valid CRAB project directory.
ERROR 2019-04-21 03:39:31,338: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 586, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_Run2018A/crab_Bparking_Run2018Als is not a valid CRAB project directory.
